### ISSUE TITLE
[BUG] admin 계정 가입 가능

### ISSUE THREAD

**Issue by DNATUNA** [BcGee/js-shop#7]
회원 가입 시 아이디 중복 검사를 하지 않아 admin 계정을 무제한으로 만들어 낼 수 있습니다.

이렇게 생성한 계정으로 로그인 시 admin 권한을 얻게 됩니다.

생성한 아이디 리스트
- admin / 98765431
- admin / qwerpoiu
- 등등

![image](https://user-images.githubusercontent.com/28949165/120104441-5e35cb80-c18f-11eb-8721-9160fef9810a.png)

**Comment by Yaaho** [comment]
가입 시 아이디 중복 검사 기능을 넣는 것으로 해결했습니다.
